### ISSUE TITLE
LESS instead of Sass?

### ISSUE THREAD

**Issue by nate-vukovich** [bassjobsen/bootstrap-cli#1]
This isn't a Issue per-se but a question if you are thinking of using - giving the chance to use either Sass or LESS in the CLI?

Would be great if you would consider it.

I might even help you out. 

EDIT:

/*Implementing handlebars would be great.*/ Didn't check but it's already implemented seems 👍 

I'll see what I can do :)

**Comment by bassjobsen** [comment]
Hi @nvwebd thanks for your message.

This project is for Bootstrap 4 only. As you maybe know Bootstrap 4 replaces Less with Sass. Also read http://bassjobsen.weblogs.fm/no-not-switch-less-sass/. AFAIK there is no Less version for BS4 yet?

Most of the built-in templates of bootstrap-cli use Panini or nunjucks. You can easily create your own template using handlebars. Let me know when you do need help.
