### ISSUE TITLE
Errors in NPM creating a project no problem but starting not possible!

### ISSUE THREAD

**Issue by Allmedialab** [bassjobsen/bootstrap-cli#2]
Hi Bass,
Try to use the CLI (because I have your latest bootstrap 4 book), but it seems impossible to npm start or bootstrap watch a project. Other applications like Stack from Zurb work perfect.
This is the error log:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\David\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.4
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bootstrap-basic-template@0.0.1~prestart: bootstrap-basic-template@0.0.1
6 silly lifecycle bootstrap-basic-template@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle bootstrap-basic-template@0.0.1~start: bootstrap-basic-template@0.0.1
8 verbose lifecycle bootstrap-basic-template@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle bootstrap-basic-template@0.0.1~start: PATH: C:\Users\David\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\David\bootstrap-4-A\node_modules\.bin;C:\Users\David\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\David\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Norman\Npm\Bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\nodejs;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Users\David\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle bootstrap-basic-template@0.0.1~start: CWD: C:\Users\David\bootstrap-4-A
11 silly lifecycle bootstrap-basic-template@0.0.1~start: Args: [ '/d /s /c', 'grunt' ]
12 silly lifecycle bootstrap-basic-template@0.0.1~start: Returned: code: 6  signal: null
13 info lifecycle bootstrap-basic-template@0.0.1~start: Failed to exec start script
14 verbose stack Error: bootstrap-basic-template@0.0.1 start: `grunt`
14 verbose stack Exit status 6
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\David\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\David\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid bootstrap-basic-template@0.0.1
16 verbose cwd C:\Users\David\bootstrap-4-A
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\David\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v6.11.0
20 verbose npm  v5.0.4
21 error code ELIFECYCLE
22 error errno 6
23 error bootstrap-basic-template@0.0.1 start: `grunt`
23 error Exit status 6
24 error Failed at the bootstrap-basic-template@0.0.1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 6, true ]
`
Regards & Thanks,
David

**Comment by bassjobsen** [comment]
Hi David, thanks for your message. Finally i found some time to fix some issues. I've updated https://github.com/bassjobsen/empty-bootstrap-project-gulp to Bootstrap v4.0.0-beta and will test it now.
