### ISSUE TITLE
Consistent errors using bootstap cli

### ISSUE THREAD

**Issue by chrismalan** [bassjobsen/bootstrap-cli#3]
This is what happens consistently when running bootstrap new: 
`/usr/lib/node_modules/bootstrap-cli/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

SyntaxError: Unexpected token @ in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/bootstrap-cli/node_modules/bower/lib/node_modules/bower-json/lib/json.js:42:29
    at /usr/lib/node_modules/bootstrap-cli/node_modules/bower/lib/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
`
The bower.json file is created but no bower directory.  The problem seems to be Bower.
Bower also doesn't install Bootstrap.  I have to do: 

> npm install --no-optional --save-dev bootstrap@4.0.0-beta.2

after first installing popper and jquery.  'n Regte kopseer.

**Comment by bassjobsen** [comment]
Bootstrap drops bower support, also see: http://getbootstrap.com/docs/4.0/migration/#beta-2-changes
